#!/usr/bin/env python

import torch
from model import BiLSTM_CRF
from preprocess import strip_punctuation, load_training_data
from utils import text2seq, idx_words, idx_tags, tags2idx

fn = "model.pkl"

model = torch.load(fn)

data = load_training_data()
training_data = data[:100]
word2idx = idx_words(training_data)
tag2idx = idx_tags(training_data)
seq = text2seq(data[3][0], word2idx)
print(seq)
prediction = model(seq)
truth = tags2idx(data[3][1], tag2idx)
print(truth)
truth = truth.resize(1, truth.size()[0])
print(truth)
print(prediction)


print(tag2idx)
sequence = text2seq(strip_punctuation("I have a migraine sore throat and sometimes tired and moody").split(), word2idx)
prediction = model(sequence)
print(prediction)
